---
openapi: 3.0.3
info:
  title: openttd-server API
  version: 1.0.0-SNAPSHOT
paths:
  /api/auth/login:
    post:
      tags:
      - Auth Resource
      responses:
        "200":
          description: OK
  /api/auth/logout:
    post:
      tags:
      - Auth Resource
      parameters:
      - name: X-OPENTTD_SERVER_SESSION_ID
        in: header
        schema:
          type: string
      responses:
        "200":
          description: OK
  /api/auth/verifyLogin:
    post:
      tags:
      - Auth Resource
      parameters:
      - name: X-OPENTTD_SERVER_SESSION_ID
        in: header
        schema:
          type: string
      responses:
        "200":
          description: OK
  /api/chunk-upload:
    post:
      tags:
      - Chunk Upload Resource
      parameters:
      - name: fileName
        in: query
        schema:
          type: string
      - name: fileSize
        in: query
        schema:
          format: int32
          type: integer
      - name: offset
        in: query
        schema:
          format: int32
          type: integer
      - name: type
        in: query
        schema:
          $ref: '#/components/schemas/ServerFileType'
      requestBody:
        content:
          application/octet-stream:
            schema:
              format: binary
              type: string
      responses:
        "200":
          description: OK
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/command:
    post:
      tags:
      - Openttd Server Resource
      operationId: executeCommand
      parameters:
      - name: name
        in: query
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Command'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Command'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/config:
    get:
      tags:
      - Openttd Server Resource
      operationId: getOpenttdServerConfig
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServerConfigGet'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
    patch:
      tags:
      - Openttd Server Resource
      operationId: updateOpenttdServerConfig
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenttdServerConfigUpdate'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServerConfigGet'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/dump:
    post:
      tags:
      - Openttd Server Resource
      operationId: dump
      parameters:
      - name: dir
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/files:
    get:
      tags:
      - Openttd Server Resource
      operationId: getServerFiles
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServerFile'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/processes:
    get:
      tags:
      - Openttd Server Resource
      operationId: processes
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OpenttdProcess'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/save:
    post:
      tags:
      - Openttd Server Resource
      operationId: save
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/send-terminal-command:
    post:
      tags:
      - Openttd Server Resource
      operationId: send-terminal-command
      parameters:
      - name: name
        in: query
        schema:
          type: string
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/server:
    get:
      tags:
      - Openttd Server Resource
      operationId: getServer
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServer'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
    put:
      tags:
      - Openttd Server Resource
      operationId: updateServer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenttdServer'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServer'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
    post:
      tags:
      - Openttd Server Resource
      operationId: addServer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OpenttdServer'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServer'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
    delete:
      tags:
      - Openttd Server Resource
      operationId: deleteServer
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/start-server:
    post:
      tags:
      - Openttd Server Resource
      operationId: start
      parameters:
      - name: config
        in: query
        schema:
          type: string
      - name: name
        in: query
        schema:
          type: string
      - name: port
        in: query
        schema:
          format: int32
          type: integer
      - name: savegame
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdProcess'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/start-server2:
    post:
      tags:
      - Openttd Server Resource
      operationId: startServer
      parameters:
      - name: name
        in: query
        schema:
          type: string
      - name: savegame
        in: query
        schema:
          type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OpenttdServer'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/stop-server:
    post:
      tags:
      - Openttd Server Resource
      operationId: stop
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "201":
          description: Created
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/openttd-server/terminal/ui-open:
    get:
      tags:
      - Openttd Server Resource
      operationId: terminalOpenInUi
      parameters:
      - name: name
        in: query
        schema:
          type: string
      responses:
        "204":
          description: No Content
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/test/exportModel:
    get:
      tags:
      - Test Resource
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExportModel'
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/test/hello:
    get:
      tags:
      - Test Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
  /api/test/hello2:
    get:
      tags:
      - Test Resource
      responses:
        "200":
          description: OK
          content:
            text/plain:
              schema:
                type: string
        "401":
          description: Not Authorized
        "403":
          description: Not Allowed
      security:
      - SecurityScheme:
        - login_user
components:
  schemas:
    BaseProcess:
      type: object
      properties:
        processId:
          type: string
        processData:
          type: string
    Command:
      type: object
      properties:
        marker:
          type: string
        command:
          type: string
        rawResult:
          type: string
        executed:
          type: boolean
        cmdSend:
          type: boolean
        type:
          type: string
    ExportModel:
      type: object
      properties:
        openttdTerminalUpdateEvent:
          $ref: '#/components/schemas/OpenttdTerminalUpdateEvent'
        unpauseCommand:
          $ref: '#/components/schemas/UnpauseCommand'
        pauseCommand:
          $ref: '#/components/schemas/PauseCommand'
        serviceError:
          $ref: '#/components/schemas/ServiceError'
    OpenttdProcess:
      type: object
      properties:
        startServerCommand:
          type: array
          items:
            type: string
        name:
          type: string
        port:
          format: int32
          type: integer
        saveGame:
          type: string
        config:
          type: string
        process:
          $ref: '#/components/schemas/BaseProcess'
        uiTerminalOpenedByClient:
          type: boolean
    OpenttdServer:
      type: object
      properties:
        name:
          type: string
        port:
          format: int32
          type: integer
        saveGame:
          $ref: '#/components/schemas/ServerFile'
        autoSaveGame:
          $ref: '#/components/schemas/ServerFile'
        startSaveGame:
          $ref: '#/components/schemas/ServerFile'
        config:
          $ref: '#/components/schemas/ServerFile'
        process:
          $ref: '#/components/schemas/OpenttdProcess'
    OpenttdServerConfigGet:
      type: object
      properties:
        autoSaveMinutes:
          format: int32
          type: integer
        servers:
          type: array
          items:
            $ref: '#/components/schemas/OpenttdServer'
    OpenttdServerConfigUpdate:
      type: object
      properties:
        autoSaveMinutes:
          format: int32
          type: integer
        password:
          type: string
        oldPassword:
          type: string
    OpenttdTerminalUpdateEvent:
      type: object
      properties:
        created:
          format: int64
          type: integer
        clazz:
          type: object
        source:
          type: string
        processId:
          type: string
        text:
          type: string
    PauseCommand:
      type: object
      properties:
        marker:
          type: string
        command:
          type: string
        rawResult:
          type: string
        executed:
          type: boolean
        cmdSend:
          type: boolean
        type:
          type: string
    ServerFile:
      type: object
      properties:
        path:
          type: string
        name:
          type: string
        type:
          $ref: '#/components/schemas/ServerFileType'
        exists:
          type: boolean
        created:
          format: int64
          type: integer
        lastModified:
          format: int64
          type: integer
    ServerFileType:
      enum:
      - SAVE_GAME
      - CONFIG
      type: string
    ServiceError:
      type: object
      properties:
        type:
          $ref: '#/components/schemas/ServiceErrorType'
        message:
          type: string
        stackTrace:
          type: string
    ServiceErrorType:
      enum:
      - VALIDATION_EXCEPTION
      - RUNTIME_EXCEPTION
      - UNKNOWN
      type: string
    UnpauseCommand:
      type: object
      properties:
        marker:
          type: string
        command:
          type: string
        rawResult:
          type: string
        executed:
          type: boolean
        cmdSend:
          type: boolean
        type:
          type: string
  securitySchemes:
    SecurityScheme:
      type: http
      description: Authentication
      scheme: basic
